services:
  backend:
    image: ghcr.io/ssciwr/circuit_seq_backend:${CIRCUIT_SEQ_DOCKER_IMAGE_TAG:-latest}
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ${CIRCUIT_SEQ_DATA:-./docker_volume}:/circuit_seq_data
      - ${CIRCUIT_SEQ_SSL_CERT:-./cert.pem}:/circuit_seq_ssl_cert.pem
      - ${CIRCUIT_SEQ_SSL_KEY:-./key.pem}:/circuit_seq_ssl_key.pem
    environment:
      - JWT_SECRET_KEY=${CIRCUIT_SEQ_JWT_SECRET_KEY:-}
  frontend:
    image: ghcr.io/ssciwr/circuit_seq_frontend:${CIRCUIT_SEQ_DOCKER_IMAGE_TAG:-latest}
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${CIRCUIT_SEQ_SSL_CERT:-./cert.pem}:/circuit_seq_ssl_cert.pem
      - ${CIRCUIT_SEQ_SSL_KEY:-./key.pem}:/circuit_seq_ssl_key.pem
  email:
    image: "boky/postfix"
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS="true"
