services:
  backend:
    image: ghcr.io/ssciwr/sample_flow_backend:${SAMPLE_FLOW_DOCKER_IMAGE_TAG:-latest}
    build: ./backend
    volumes:
      - ${SAMPLE_FLOW_DATA:-./docker_volume}:/sample_flow_data
    environment:
      - JWT_SECRET_KEY=${SAMPLE_FLOW_JWT_SECRET_KEY:-}
  frontend:
    image: ghcr.io/ssciwr/sample_flow_frontend:${SAMPLE_FLOW_DOCKER_IMAGE_TAG:-latest}
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${SAMPLE_FLOW_SSL_CERT:-./cert.pem}:/sample_flow_ssl_cert.pem
      - ${SAMPLE_FLOW_SSL_KEY:-./key.pem}:/sample_flow_ssl_key.pem
  email:
    image: "boky/postfix"
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS="true"
